---
- name: full combo
  hosts: lhost

  tasks:
    - name: git pull
      git:
        repo: https://github.com/an-nikolaev/kols-test.git
        dest: /home/ibljad/tests/ansible/kols-test

    - name: build tests
      shell:
        cmd: mvn clean package
        chdir: target


    - name: run tests script
      shell:
        chdir: target
        cmd: bash run.sh
